# Welcome to Jekyll!
#

# Site settings
title: UC Jazz

description: |
  UC Jazz Ensembles is dedicated to the  
  performance, study, and promotion of  
  jazz at UC Berkeley.

owner: UC Jazz # or company name
#first_published: 2016 # if migrating another site, the year of your first publish
email: tmoore@ucjazz.berkeley.edu 

# # for staging on github pages
# baseurl: "/ucjazz_site" # the subpath of your site, e.g. /blog

# for local development
baseurl: "/"

url: "https://treyfortmuller.github.io/ucjazz_site/" # the base hostname & protocol for your site

# social outlets for the site
facebook: https://facebook.com/ucjazz/
soundcloud: https://soundcloud.com/user-856784552
youtube: https://www.youtube.com/channel/UCCU3aQp9KnJH8DFwLNzwqbw
wikipedia: https://en.wikipedia.org/wiki/University_of_California_Jazz_Ensembles

# Build settings
markdown: kramdown
#sass:
#  style: compressed
